pipeline {
  agent any
  tools {
    jdk 'JDK17' 
    maven 'M3'
  }
  options { timestamps() }
  triggers { githubPush() }
  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }
    stage('Build & Test') {
      steps {
        sh 'mvn -B -U -Dmaven.test.failure.ignore=false clean verify'
      }
      post {
        always {
          junit 'target/surefire-reports/*.xml'
        }
      }
    }
    stage('Package') {
      steps {
        sh 'mvn -B package -DskipTests'
        archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
      }
    }
  }
}

